version: "3.9"

services:
  api:
    build: ./indexesview/
    container_name: indexesview_api
    ports:
      - 8000:8000
    environment:
      STORAGE: "./indesesview/static"
    volumes:
      - ./server/static:/api/static
    restart: always

#  worker_celery:
#    restart: always
#    build: ./indexesview/
#    container_name: worker_celery
#
#    command: [ 'celery', '--workdir=../indexesview', '-A', 'indexesview', 'worker' ]
  postgres:
    build: ./postgresql
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "indexesview_db"
      POSTGRES_USER: "indexesview"
      POSTGRES_PASSWORD: "iNdEx3es49Vi2e@w"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresql/postgres-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U indexesview -d indexesview_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G


#  redis:
#    image: redis
#    restart: always
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    ports:
#        - 5672:5672
#        - 15672:15672
#    volumes:
#        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
#    expose:
#      - 5672
#      - 15672
